// flow-typed signature: 76d2d3da00c78f06ef1b98089977b45d
// flow-typed version: <<STUB>>/draft-js-prism_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-prism/demo/main' {
  declare module.exports: any;
}

declare module 'draft-js-prism/lib/__tests__/index' {
  declare module.exports: any;
}

declare module 'draft-js-prism/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-prism/lib/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-prism/demo/main.js' {
  declare module.exports: $Exports<'draft-js-prism/demo/main'>;
}
declare module 'draft-js-prism/lib/__tests__/index.js' {
  declare module.exports: $Exports<'draft-js-prism/lib/__tests__/index'>;
}
declare module 'draft-js-prism/lib/index.js' {
  declare module.exports: $Exports<'draft-js-prism/lib/index'>;
}
declare module 'draft-js-prism/lib/options.js' {
  declare module.exports: $Exports<'draft-js-prism/lib/options'>;
}
